export const REPOSITORY_SETS_REQUEST = 'REPOSITORY_SETS_REQUEST';
export const REPOSITORY_SETS_SUCCESS = 'REPOSITORY_SETS_SUCCESS';
export const REPOSITORY_SETS_FAILURE = 'REPOSITORY_SETS_FAILURE';

export const PRODUCT_REPOSITORY_SETS_REQUEST = 'PRODUCT_REPOSITORY_SETS_REQUEST';
export const PRODUCT_REPOSITORY_SETS_SUCCESS = 'PRODUCT_REPOSITORY_SETS_SUCCESS';
export const PRODUCT_REPOSITORY_SETS_FAILURE = 'PRODUCT_REPOSITORY_SETS_FAILURE';

export const ENABLED_REPOSITORIES_REQUEST = 'ENABLED_REPOSITORIES_REQUEST';
export const ENABLED_REPOSITORIES_SUCCESS = 'ENABLED_REPOSITORIES_SUCCESS';
export const ENABLED_REPOSITORIES_FAILURE = 'ENABLED_REPOSITORIES_FAILURE';

export const REPOSITORY_SET_REPOSITORIES_REQUEST = 'REPOSITORY_SET_REPOSITORIES_REQUEST';
export const REPOSITORY_SET_REPOSITORIES_SUCCESS = 'REPOSITORY_SET_REPOSITORIES_SUCCESS';
export const REPOSITORY_SET_REPOSITORIES_FAILURE = 'REPOSITORY_SET_REPOSITORIES_FAILURE';

export const REPOSITORY_ENABLED = 'REPOSITORY_ENABLED';
export const REPOSITORY_DISABLED = 'REPOSITORY_DISABLED';

export const TABLE_COLUMNS_REQUEST = 'TABLE_COLUMNS_REQUEST';
export const TABLE_COLUMNS_SUCCESS = 'TABLE_COLUMNS_SUCCESS';
export const TABLE_COLUMNS_FAILURE = 'TABLE_COLUMNS_FAILURE';

export const CREATE_TABLE_COLUMNS = 'CREATE_TABLE_COLUMNS';
export const CREATE_TABLE_COLUMNS_SUCCESS = 'CREATE_TABLE_COLUMNS_SUCCESS';
export const CREATE_TABLE_COLUMNS_FAILURE = 'CREATE_TABLE_COLUMNS_FAILURE';

export const UPDATE_TABLE_COLUMNS = 'UPDATE_TABLE_COLUMNS';
export const UPDATE_TABLE_COLUMNS_SUCCESS = 'UPDATE_TABLE_COLUMNS_SUCCESS';
export const UPDATE_TABLE_COLUMNS_FAILURE = 'UPDATE_TABLE_COLUMNS_FAILURE';


export const DELETE_TABLE_COLUMNS = 'DELETE_TABLE_COLUMNS';
export const DELETE_TABLE_COLUMNS_SUCCESS = 'DELETE_TABLE_COLUMNS_SUCCESS';
export const DELETE_TABLE_COLUMNS_FAILURE = 'DELETE_TABLE_COLUMNS_FAILURE';
